### ISSUE TITLE
Unable to add to Docker Compose

### ISSUE THREAD

**Issue by R0ltec** [ParinLL/cyberpower-ups-exporter#2]
I am not great at this but something seems off. The code you have for the docker compose file contains no image and no repository to download from. So how is this supposed to work?

**Comment by Jyny** [comment]
@ParinLL PTAL

**Comment by R0ltec** [comment]
What in the world is that supposed to mean?

**Comment by ParinLL** [comment]
Hi @R0ltec 

In fact, Docker Compose supports building and using images locally. Therefore, you can clone this repo and then directly execute this command. Docker will automatically build an image and run it :
```
docker compose up --build
```

If you need an image that can be used immediately, you can refer to [dokfish/cyberpower-exporter](https://hub.docker.com/r/dokfish/cyberpower-exporter)

Hope the above information is helpful to you.

**Comment by R0ltec** [comment]
Thank you, that helped me. Was then able to put the information together and build the following to work with docker compose and a cyberpower UPS using a rmcard205 in my case:

  cyberpower-ups-exporter-1:
    image: dokfish/cyberpower-exporter:v0.1.1
    container_name: cyberpower-ups-exporter-1
    networks:
      - monitoring
    ports:
      - "9101:9101"
    environment:
      - SNMP_TARGET=192.168.1.210
      - SNMP_PORT=161
      - SNMP_COMMUNITY=public
      - SERVER_PORT=9101
    restart: unless-stopped

This is my Compose. The ports and server ports can be changed as needed as in my case I have multiple UPS's online. Past this, just add this target into prometheus.yml and import the dashboard provided! Working great, thank you for making this! I would suggest placing my info in the front page to help those who aren't as savvy as even I don't know how to build stuff yet as you mentioned above.
